### ISSUE TITLE
Pre-Reqs instructions refer to <prefix> using in Ingest phase.

### ISSUE THREAD

**Issue by mriggs78729** [jingalls1217/opendatalakehouse#27]
The prereqs [instructions](https://github.com/jingalls1217/opendatalakehouse/blob/master/00_prereqs.md) refer to the <prefix> for the table name in Lab 3 Step 2.  Seems like we should define what we want to prefix to be here and refer back to it in the ingest phase.

**Comment by dnirchi** [comment]
Good catch. We mention "come up with a prefix" at the start of [01_ingest - Lab 1](https://github.com/jingalls1217/opendatalakehouse/blob/master/01_ingest.md), but this statement really belongs in [00_prereqs](https://github.com/jingalls1217/opendatalakehouse/blob/master/00_prereqs.md).
